#ifndef _MELEE_H
#define _MELEE_H

enum
{
    MELEE_ANDROSYNTH,
    MELEE_ARILOU,
    MELEE_CHENJESU,
    MELEE_CHMMR,
    MELEE_DRUUGE,
    MELEE_EARTHLING,
    MELEE_ILWRATH,
    MELEE_KOHR_AH,
    MELEE_MELNORME,
    MELEE_MMRNMHRM,
    MELEE_MYCON,
    MELEE_ORZ,
    MELEE_PKUNK,
    MELEE_SHOFIXTI,
    MELEE_SLYLANDRO,
    MELEE_SPATHI,
    MELEE_SUPOX,
    MELEE_SYREEN,
    MELEE_THRADDASH,
    MELEE_UMGAH,
    MELEE_URQUAN,
    MELEE_UTWIG,
    MELEE_VUX,
    MELEE_YEHAT,
    MELEE_ZOQFOTPIK,
    
    NUM_MELEE_SHIPS
};

#define NUM_MELEE_ROWS		2
// #define NUM_MELEE_COLUMNS	7
#define NUM_MELEE_COLUMNS	6
#define ICON_WIDTH		16
#define ICON_HEIGHT		16

extern FRAME			PickMeleeFrame;

#define PICK_BG_COLOR		BUILD_COLOR (MAKE_RGB15 (0x00, 0x01, 0x0F), 0x1)

#endif /* _MELEE_H */

